# Generated by Django 5.0.6 on 2024-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='localizacao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('Contador', 'Contador'), ('Luminosidade', 'Luminosidade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
