# Generated by Django 5.0.6 on 2024-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_alter_sensor_mac_address_alter_sensor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
